parameters:
   btn_app.game_manager.class: Btn\AppBundle\Service\GameManager

services:
   btn_app.game:
       class: %btn_app.game_manager.class%
       arguments:
            - @mailer
            - @doctrine.orm.entity_manager
            - %admin_email%
            - @templating
            - @session
